/* generated by unplugin-react-components */
export {}
declare global{
	const About: typeof import('./src/components/About/About')['default']
	const Contact: typeof import('./src/components/Contact/Contact')['default']
	const Footer: typeof import('./src/components/Footer/Footer')['default']
	const Home: typeof import('./src/components/Home/Home')['default']
	const Navbar: typeof import('./src/components/Navbar/Navbar')['default']
	const Portfolio: typeof import('./src/components/Portfolio/Portfolio')['default']
}